### ISSUE TITLE
License File Not Being Detected

### ISSUE THREAD

**Issue by aidan-epperly** [LLNL/wcs#20]
It seems like GitHub is not properly detecting the license file and registering it. This impacts some of the data on [software.llnl.gov](http://software.llnl.gov) as we use license information for one of our graphics, though it should not negatively affect anything else.

**Comment by JaeseungYeom** [comment]
The license file seems readable on my end.
Let me know if there is any suggested action item.

**Comment by aidan-epperly** [comment]
I tried a number of different things from using GitHub's own MIT template to copying the licence from another LLNL repository, and for some reason GitHub is still failing to recognize the license. I will try to figure it out why this is with the [licensee](https://github.com/licensee/licensee) repository and get back to you.

**Comment by IanLee1521** [comment]
Looking in to the licensee output, it looks like the COPYRIGHT file is messing but the result... Is there a reason for that COPYRIGHT file?

```
root@d182375cc382:/# licensee detect https://github.com/LLNL/wcs
License:        NOASSERTION
Matched files:  LICENSE, COPYRIGHT
LICENSE:
  Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution:   Copyright (c) 2020, Lawrence Livermore National Security, LLC
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
COPYRIGHT:
  Content hash:  4023e4642021db85af511aa8f8ef02e11411a9b2
  License:       NOASSERTION
  Closest non-matching licenses:
    WTFPL similarity:  16.90%
    ISC similarity:    13.04%
    Zlib similarity:   11.76%
```

**Comment by IanLee1521** [comment]
Note that the lab guidance on license / notice files can be found: https://software.llnl.gov/about/licenses/

**Comment by JaeseungYeom** [comment]
Should I remove COPYRIGHT file? The reason I have it is that both the example repos (spack, cardioid) referenced by the above page have that file. I was following the examples.

**Comment by IanLee1521** [comment]
yes, would you mind removing it? I'm curious to see if the dual license detection works better if the copyright is not there.

**Comment by JaeseungYeom** [comment]
If the removal of the file resolved the issue, I will close this.

**Comment by IanLee1521** [comment]
Looks like it did, now detecting correctly as MIT:

![image](https://user-images.githubusercontent.com/828452/89353404-25aa8b80-d66b-11ea-9c06-b5edf572a377.png)

**Comment by JaeseungYeom** [comment]
Great!

**Comment by IanLee1521** [comment]
Yes, thank you!
